# Uso de Dataframe en Pandas
##### https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

In [1]:
import pandas as pd
import sys
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

%matplotlib inline

In [4]:
data1 = pd.read_csv("data/personas_fake.csv", sep="|")
data1

,id,nombre,apellido,pais,direccion
0,3222303,Kim,Crawford,AM,"3921 Nicole Rapid-West Michael, NC 18388"
1,893117,Michael,Morales,BJ,"58502 Michelle Key-North Nicole, MO 55326"
2,7662650,Jacob,Mosley,MW,"163 Farley Well-East Lisa, LA 56846"
3,8008659,Dawn,Brandt,CU,"502 Stephanie Lodge-Lake Antonioton, WY 41486"
4,994528,John,Lee,ET,"4178 Amber Canyon Apt. 826-Lake Nichole, NV 41277"
...,...,...,...,...,...
763,5536611,Renee,Acosta,HU,"305 Jay Corners Suite 555-South Nichole, VI 43882"
764,34019,Alyssa,Pollard,KI,"36864 Taylor Ramp-Moodyside, PA 10697"
765,620314,Noah,Strickland,BS,"903 Cindy Gardens-Markshire, AK 21081"
766,7629094,Matthew,Christensen,NI,"09762 Reyes Vista Suite 283-East Georgefurt, M..."
767,473565,Michael,Hernandez,FJ,Unit 7923 Box 0469-DPO AP 16796

In [10]:
data1[data1.nombre=="Jacob"]

,id,nombre,apellido,pais,direccion
2,7662650,Jacob,Mosley,MW,"163 Farley Well-East Lisa, LA 56846"
594,7788937,Jacob,Meyers,CO,"62112 Christina Burg-Petersonmouth, WA 31575"
673,789355,Jacob,Rowland,KG,"672 Petersen Mountain Suite 806-Laurashire, FL..."

In [13]:
data1.dtypes

id            int64
nombre       object
apellido     object
pais         object
direccion    object
dtype: object

In [14]:
data1[(data1.nombre=="Jacob") & (data1.pais=="CO")]

,id,nombre,apellido,pais,direccion
594,7788937,Jacob,Meyers,CO,"62112 Christina Burg-Petersonmouth, WA 31575"